import Footer from "@/Components/Footer";
import Header from "@/Components/Header";
import store from "@/store/store";

import "@/styles/globals.css";
import Head from "next/head";
import { Provider } from "react-redux";


export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Online Shoe Store | CodeAri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&family=Oswald:wght@200;400;500;600&family=Urbanist:wght@100;300;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
    <Provider store={store}>
    <Header />
        <Component {...pageProps} />
        <Footer />
    </Provider>
      

    </>
  );
}
